services:
  server:
    build: .
    environment:
      - PORT=3000
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USERNAME=user
      - PG_PASSWORD=password
      - PG_DB=user
      - JWT_SECRET_KEY=secret_key
    ports:
      - "8080:3000"
    networks:
      - database
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:
    driver: bridge
