export const configLiterals = {
  HASH_SALT_ROUNDS: "HASH_SALT_ROUNDS",
  PORT: "PORT",
  PG_USERNAME: "PG_USERNAME",
  PG_PASSWORD: "PG_PASSWORD",
  PG_HOST: "PG_HOST",
  PG_PORT: "PG_PORT",
  PG_DB: "PG_DB",
};
